modLoader = "javafml"
loaderVersion = "[4,)"
license="MIT"
credits="Fork of Armor of the Ages by AlxR00T. Maintained by Stalking Dragons."

[[mods]]
modId="ageforged_armor"
version="0.0.0-beta.37"
displayName="Ageforged Armor"
logoFile="ageforged_armor.png"

[[mixins]]
config = "ageforged_armor.mixins.json"

[[mixins]]
config = "ageforged_armor.neoforge.mixins.json"

[[dependencies.ageforged_armor]]
modId="neoforge"
type="required"
versionRange="[26.1.2.78,)"
ordering="NONE"
side="BOTH"

[[dependencies.ageforged_armor]]
modId="minecraft"
type="required"
versionRange="[26.1.2]"
ordering="NONE"
side="BOTH"

[[dependencies.ageforged_armor]]
modId="yet_another_config_lib_v3"
type="required"
versionRange="[3.0,)"
ordering="NONE"
side="CLIENT"
